disabled_rules: # rule identifiers turned on by default to exclude from running
  # general
  # single word related
  - inclusive_language
  - identifier_name
  - type_name
  # multiple word length related
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  # too complicated
  - multiple_closures_with_trailing_closure
  # add unnecessary complexity, current implementations works fine
  - class_delegate_protocol
  - force_cast
  - force_try
  - large_tuple

statement_position:
  statement_mode: uncuddled_else