USE Hound;
TRUNCATE TABLE users;
TRUNCATE TABLE userConfiguration;
TRUNCATE TABLE familyMembers;
TRUNCATE TABLE families;
TRUNCATE TABLE dogs;
TRUNCATE TABLE dogLogs;
TRUNCATE TABLE dogReminders;
TRUNCATE TABLE userRequestLogs;
TRUNCATE TABLE subscriptions; 
