INSERT INTO log_types (type_name) VALUES ('Custom');
INSERT INTO log_types (type_name) VALUES ('Feed');
INSERT INTO log_types (type_name) VALUES ('Fresh Water');
INSERT INTO log_types (type_name) VALUES ('Treat');
INSERT INTO log_types (type_name) VALUES ('Potty: Pee');
INSERT INTO log_types (type_name) VALUES ('Potty: Poo');
INSERT INTO log_types (type_name) VALUES ('Potty: Didn''t Go');
INSERT INTO log_types (type_name) VALUES ('Accident');
INSERT INTO log_types (type_name) VALUES ('Walk');
INSERT INTO log_types (type_name) VALUES ('Brush');
INSERT INTO log_types (type_name) VALUES ('Bathe');
INSERT INTO log_types (type_name) VALUES ('Medicine');
INSERT INTO log_types (type_name) VALUES ('Wake Up');
INSERT INTO log_types (type_name) VALUES ('Sleep');
INSERT INTO log_types (type_name) VALUES ('Crate');
INSERT INTO log_types (type_name) VALUES ('Training Session');
INSERT INTO log_types (type_name) VALUES ('Doctor Visit');

INSERT INTO reminder_types (type_name) VALUES ('Custom');
INSERT INTO reminder_types (type_name) VALUES ('Feed');
INSERT INTO reminder_types (type_name) VALUES ('Potty');
INSERT INTO reminder_types (type_name) VALUES ('Walk');
INSERT INTO reminder_types (type_name) VALUES ('Brush');
INSERT INTO reminder_types (type_name) VALUES ('Bathe');
INSERT INTO reminder_types (type_name) VALUES ('Medicine');
INSERT INTO reminder_types (type_name) VALUES ('Sleep');
INSERT INTO reminder_types (type_name) VALUES ('Training Session');
INSERT INTO reminder_types (type_name) VALUES ('Doctor Visit');